// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9K-1Z8E7yBJ7X_tAQfsOjpd1J2xTQHO4',
    appId: '1:1081985017914:web:83fac256f617be78b46d03',
    messagingSenderId: '1081985017914',
    projectId: 'sikkim-tourism-a9036',
    authDomain: 'sikkim-tourism-a9036.firebaseapp.com',
    storageBucket: 'sikkim-tourism-a9036.firebasestorage.app',
    measurementId: 'G-1QXEYS6XL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WLlGRGmxCrJbuud3nx8c1aIrvOaN7Cg',
    appId: '1:1081985017914:android:d3556dd54f6b0b7bb46d03',
    messagingSenderId: '1081985017914',
    projectId: 'sikkim-tourism-a9036',
    storageBucket: 'sikkim-tourism-a9036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0UtTgw_nhwDy5ltURpHNxnCoBcieEKWQ',
    appId: '1:1081985017914:ios:6310a4371aea9d1bb46d03',
    messagingSenderId: '1081985017914',
    projectId: 'sikkim-tourism-a9036',
    storageBucket: 'sikkim-tourism-a9036.firebasestorage.app',
    iosBundleId: 'com.example.sikkimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0UtTgw_nhwDy5ltURpHNxnCoBcieEKWQ',
    appId: '1:1081985017914:ios:6310a4371aea9d1bb46d03',
    messagingSenderId: '1081985017914',
    projectId: 'sikkim-tourism-a9036',
    storageBucket: 'sikkim-tourism-a9036.firebasestorage.app',
    iosBundleId: 'com.example.sikkimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9K-1Z8E7yBJ7X_tAQfsOjpd1J2xTQHO4',
    appId: '1:1081985017914:web:2547022ed77a224cb46d03',
    messagingSenderId: '1081985017914',
    projectId: 'sikkim-tourism-a9036',
    authDomain: 'sikkim-tourism-a9036.firebaseapp.com',
    storageBucket: 'sikkim-tourism-a9036.firebasestorage.app',
    measurementId: 'G-NT8TY522QV',
  );
}
