// Enhanced September festivals data
const additionalSeptemberEvents = [
  {
    id: 'sep-extra-1',
    title: 'Indra Jatra Festival',
    description: 'Festival honoring Lord Indra with traditional dances and rituals',
    date: '2024-09-08',
    category: 'Festival',
    location: 'Namchi, Sikkim',
    time: '09:00 AM',
    color: 'bg-purple-500',
    monthDay: 8,
  },
  {
    id: 'sep-extra-2',
    title: 'Himalayan Heritage Festival',
    description: 'Celebration of Himalayan culture with folk music, dance, and local cuisine',
    date: '2024-09-12',
    category: 'Cultural',
    location: 'Yuksom, Sikkim',
    time: '11:00 AM',
    color: 'bg-blue-500',
    monthDay: 12,
  },
  {
    id: 'sep-extra-3',
    title: 'Dussehra Celebrations',
    description: 'Grand celebration of victory of good over evil with cultural programs',
    date: '2024-09-15',
    category: 'Festival',
    location: 'Gyalshing, Sikkim',
    time: '06:00 PM',
    color: 'bg-red-500',
    monthDay: 15,
  },
  {
    id: 'sep-extra-4',
    title: 'Sikkimese Cuisine Festival',
    description: 'Culinary extravaganza showcasing authentic Sikkimese dishes and cooking traditions',
    date: '2024-09-18',
    category: 'Food',
    location: 'Mangan, Sikkim',
    time: '12:00 PM',
    color: 'bg-yellow-500',
    monthDay: 18,
  },
  {
    id: 'sep-extra-5',
    title: 'Monastery Art Exhibition',
    description: 'Display of traditional Tibetan and Buddhist art from local monasteries',
    date: '2024-09-21',
    category: 'Art',
    location: 'Rumtek Monastery, Sikkim',
    time: '10:00 AM',
    color: 'bg-indigo-500',
    monthDay: 21,
  },
  {
    id: 'sep-extra-6',
    title: 'Lepcha Heritage Day',
    description: 'Celebration of Lepcha indigenous culture with traditional rituals and performances',
    date: '2024-09-24',
    category: 'Cultural',
    location: 'Dzongu, Sikkim',
    time: '09:00 AM',
    color: 'bg-green-500',
    monthDay: 24,
  },
  {
    id: 'sep-extra-7',
    title: 'Autumn Harvest Festival',
    description: 'Community celebration of the autumn harvest with local produce exhibition',
    date: '2024-09-27',
    category: 'Festival',
    location: 'Ravangla, Sikkim',
    time: '08:00 AM',
    color: 'bg-orange-500',
    monthDay: 27,
  },
  {
    id: 'sep-extra-8',
    title: 'Traditional Mask Dance Festival',
    description: 'Spectacular display of traditional Cham dances with ornate masks',
    date: '2024-09-30',
    category: 'Dance',
    location: 'Pemayangtse Monastery, Sikkim',
    time: '02:00 PM',
    color: 'bg-pink-500',
    monthDay: 30,
  },
];

// Export for use in events generation
export { additionalSeptemberEvents };